### ISSUE TITLE
Add preloader 

### ISSUE THREAD

**Issue by theobiabo** [Bookhive-Club/Bookhive-Client#16]
#### Add a preloader

* Preloader should should when any page is loading 
* Preloader should disappear as soon as the page is loaded

**Comment by praptisharma28** [comment]
please assign me this.

**Comment by theobiabo** [comment]
Awesome, Issue has been assigned to you

**Comment by theobiabo** [comment]
@praptisharma28 when you are done, Raise a PR to dev branch

**Comment by theobiabo** [comment]
ji @praptisharma28 how is it going

**Comment by purnasth** [comment]
If this is still an issue, I can work on it.

**Comment by theobiabo** [comment]
Hey @purnasth thanks alot, i think @praptisharma28 is still working on it, lets confirm from her first. 

If no then it will be reassigned to you

**Comment by praptisharma28** [comment]
Asssign him @yhoungdev !

**Comment by theobiabo** [comment]
ok

**Comment by theobiabo** [comment]
hey @purnasth i will be assigning this to you

**Comment by purnasth** [comment]
Hello, @yhoungdev!
Using the hooks, we can add a preloader to the website. However, because the hooks are Server Components by default, we must declare "use client" in order to utilize useState in this project. 
Marking the "use client" creates an issue with metadata as The Next.js 'metadata' API is not allowed in a client component.

It is therefore impossible to have a preloader without any problems.
This is the preloader I used for the project, and it does exactly what you asked it to: it appears as soon as a page loads and functions while any page is loading.

https://github.com/Bookhive-Club/Bookhive-Client/assets/107195487/8fea00a9-426e-498d-b761-aa1180f4a54a

What should I do now—open the PR?

**Comment by theobiabo** [comment]
Hey man I like this

**Comment by theobiabo** [comment]
You know what ? Raise a PR I know how I will handle that

**Comment by purnasth** [comment]
Hi there, @yhoungdev I have opened a PR, and also feel free to share with me how you would resolve this issue as well.

**Comment by theobiabo** [comment]
Yea sure. this is a way to acheive that and make it work globally. 

We are using React 13 App directory, which renders everything on the server side by default. so to archieve the the preloader with out an issue is. you need to create a loading.tsx file in the root of  /app , the loading.tsx file will container your preloader code

**Comment by theobiabo** [comment]
with this NextJs will treat it just like how it treats error.tsx, page.tsx, layout.tsx
  Is it clear to you ? if no let me know so i can explain better

**Comment by theobiabo** [comment]
you can checkout this on the nextjs 13 doc 

https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

let me know if you have any issues concerning that

**Comment by purnasth** [comment]
This explanation was brief yet very useful. I appreciate you taking the time to go over this with me.

**Comment by theobiabo** [comment]
Thanks alot man, dont forget to star the repo
